CREATE TABLE reservation (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(40)
);

-- INSERT INTO reservation (name) VALUES 
-- ("Frank"),
-- ("Michael"),
-- ("John"),
-- ("Maria")
-- ("Tanya");